@version: 4.2

source s_file {
  file("/tmp/messages_FW.log" follow-freq(0) flags(no-parse));
};

destination d_alloy {
  syslog("alloy" transport("udp") port(514));
};

log {
  source(s_file);
  destination(d_alloy);
};
